# Generated by Django 4.1.7 on 2023-03-14 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_date_joined_member_extra_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
    ]
