# Generated by Django 4.1.7 on 2023-03-14 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
