# Generated by Django 4.1.7 on 2023-03-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member", name="phone_number", field=models.IntegerField(),
        ),
    ]
